# Generated by Django - Initial PKI Models Migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from common.db.fields import EncryptTextField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create CertificateAuthority model
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='CA Name')),
                ('certificate', EncryptTextField(verbose_name='CA Certificate PEM')),
                ('private_key', EncryptTextField(verbose_name='CA Private Key PEM')),
                ('serial_number', models.BigIntegerField(default=1, verbose_name='Next Serial Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'db_table': 'pki_certificate_authority',
                'ordering': ['-created_at'],
            },
        ),

        # Create Certificate model
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(
                    choices=[('user', 'User Certificate'), ('service', 'Service Certificate')],
                    default='user',
                    max_length=10,
                    verbose_name='Certificate Type'
                )),
                ('serial_number', models.CharField(
                    db_index=True,
                    max_length=128,
                    unique=True,
                    verbose_name='Serial Number'
                )),
                ('certificate', EncryptTextField(verbose_name='Certificate PEM')),
                ('private_key', EncryptTextField(
                    blank=True,
                    null=True,
                    verbose_name='Private Key PEM'
                )),
                ('subject_dn', models.CharField(max_length=512, verbose_name='Subject Distinguished Name')),
                ('issuer_dn', models.CharField(max_length=512, verbose_name='Issuer Distinguished Name')),
                ('not_before', models.DateTimeField(verbose_name='Not Before')),
                ('not_after', models.DateTimeField(verbose_name='Not After')),
                ('revoked', models.BooleanField(default=False, verbose_name='Revoked')),
                ('revocation_date', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Revocation Date'
                )),
                ('revocation_reason', models.CharField(
                    blank=True,
                    max_length=256,
                    null=True,
                    verbose_name='Revocation Reason'
                )),
                ('certificate_hash', models.CharField(
                    blank=True,
                    max_length=64,
                    null=True,
                    help_text='SHA-256 hash of certificate PEM (for reissuance attack prevention)',
                    verbose_name='Certificate Hash'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ca', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='certificates',
                    to='pki.certificateauthority',
                    verbose_name='Certificate Authority'
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='certificates',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='User'
                )),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'pki_certificate',
                'ordering': ['-created_at'],
            },
        ),

        # Create CertificateRevocationList model
        migrations.CreateModel(
            name='CertificateRevocationList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('crl_pem', models.TextField(verbose_name='CRL PEM')),
                ('this_update', models.DateTimeField(verbose_name='This Update')),
                ('next_update', models.DateTimeField(verbose_name='Next Update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ca', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='crls',
                    to='pki.certificateauthority',
                    verbose_name='Certificate Authority'
                )),
            ],
            options={
                'verbose_name': 'Certificate Revocation List',
                'verbose_name_plural': 'Certificate Revocation Lists',
                'db_table': 'pki_certificate_revocation_list',
                'ordering': ['-created_at'],
            },
        ),

        # Add indexes for Certificate model
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['serial_number'], name='pki_certifi_serial__idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'revoked'], name='pki_certifi_user_re_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['not_after'], name='pki_certifi_not_aft_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_hash'], name='pki_cert_hash_idx'),
        ),
    ]
