# -*- coding: utf-8 -*-
# Generated by Django for Blockchain Chain of Custody System
# This migration creates all initial blockchain models including:
# - Investigation (case container)
# - BlockchainTransaction (blockchain transaction records)
# - Evidence (evidence file metadata)
# - GUIDMapping (anonymous GUID to user mapping)
# - Tag (admin-created categorization tags)
# - InvestigationTag (many-to-many with max 3 tags per investigation)
# - InvestigationNote (blockchain-logged investigator notes)
# - InvestigationActivity (24-hour activity tracking)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('orgs', '__first__'),
    ]

    operations = [
        # =====================================================================
        # CORE BLOCKCHAIN MODELS
        # =====================================================================
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Case Number')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived At')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='Reopened At')),
                ('reopen_reason', models.TextField(blank=True, null=True, verbose_name='Reopen Reason')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_archived', to=settings.AUTH_USER_MODEL, verbose_name='Archived By')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_reopened', to=settings.AUTH_USER_MODEL, verbose_name='Reopened By')),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'blockchain_investigation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Transaction Hash')),
                ('chain_type', models.CharField(choices=[('hot', 'Hot Chain'), ('cold', 'Cold Chain')], max_length=4, verbose_name='Chain Type')),
                ('block_number', models.BigIntegerField(blank=True, null=True, verbose_name='Block Number')),
                ('evidence_hash', models.CharField(max_length=256, verbose_name='Evidence Hash (SHA-256)')),
                ('ipfs_cid', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='IPFS CID')),
                ('user_guid', models.CharField(blank=True, max_length=256, null=True, verbose_name='User GUID (if anonymous)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('merkle_root', models.CharField(max_length=256, verbose_name='Merkle Root')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Verification Date')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.investigation', verbose_name='Investigation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'db_table': 'blockchain_transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file_name', models.CharField(max_length=512, verbose_name='File Name')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(max_length=128, verbose_name='MIME Type')),
                ('file_hash_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 Hash')),
                ('ipfs_cid', models.CharField(db_index=True, max_length=128, verbose_name='IPFS CID')),
                ('encryption_key_id', models.CharField(max_length=256, verbose_name='Encryption Key ID')),
                ('uploaded_by_guid', models.CharField(blank=True, max_length=256, null=True, verbose_name='Uploader GUID (if anonymous)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('merkle_proof', models.JSONField(default=dict, verbose_name='Merkle Proof')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='blockchain.investigation', verbose_name='Investigation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('hot_chain_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hot_evidence', to='blockchain.blockchaintransaction', verbose_name='Hot Chain Transaction')),
                ('cold_chain_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cold_evidence', to='blockchain.blockchaintransaction', verbose_name='Cold Chain Transaction')),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'db_table': 'blockchain_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GUIDMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guid', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Anonymous GUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guid_mapping', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'GUID Mapping',
                'verbose_name_plural': 'GUID Mappings',
                'db_table': 'blockchain_guid_mapping',
                'permissions': [
                    ('resolve_guid', 'Can resolve GUID to real identity'),
                ],
            },
        ),

        # =====================================================================
        # UI ENHANCEMENT MODELS (TAGS, NOTES, ACTIVITY TRACKING)
        # =====================================================================
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('category', models.CharField(choices=[('crime_type', 'Crime Type'), ('priority', 'Priority'), ('status', 'Status')], default='crime_type', max_length=50, verbose_name='Category')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color (Hex)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'blockchain_tag',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_tags', to='blockchain.investigation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_investigations', to='blockchain.tag')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'Investigation Tag',
                'verbose_name_plural': 'Investigation Tags',
                'db_table': 'blockchain_investigation_tag',
                'unique_together': {('investigation', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Note Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('note_hash', models.CharField(max_length=64, verbose_name='Note Hash (SHA-256)')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blockchain.investigation', verbose_name='Investigation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('blockchain_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='blockchain.blockchaintransaction', verbose_name='Blockchain Transaction')),
            ],
            options={
                'verbose_name': 'Investigation Note',
                'verbose_name_plural': 'Investigation Notes',
                'db_table': 'blockchain_investigation_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('evidence_added', 'Evidence Added'), ('note_added', 'Note Added'), ('tag_changed', 'Tag Changed'), ('status_changed', 'Status Changed'), ('assigned', 'Investigator Assigned')], max_length=20, verbose_name='Activity Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='blockchain.investigation', verbose_name='Investigation')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='viewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='Viewed By')),
            ],
            options={
                'verbose_name': 'Investigation Activity',
                'verbose_name_plural': 'Investigation Activities',
                'db_table': 'blockchain_investigation_activity',
                'ordering': ['-timestamp'],
            },
        ),

        # =====================================================================
        # INDEXES FOR PERFORMANCE
        # =====================================================================
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain_tx_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['chain_type', 'timestamp'], name='blockchain_tx_chain_time_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['investigation', 'chain_type'], name='blockchain_tx_inv_chain_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['ipfs_cid'], name='blockchain_tx_ipfs_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['file_hash_sha256'], name='blockchain_ev_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['ipfs_cid'], name='blockchain_ev_ipfs_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['investigation', 'uploaded_at'], name='blockchain_ev_inv_time_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationactivity',
            index=models.Index(fields=['investigation', '-timestamp'], name='blockchain_act_inv_time_idx'),
        ),
    ]
